ERROR - 2023-11-12 20:58:13 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'real_estate', 3306, '', 0)
#1 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(85): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(27): App\Controllers\Bot->getSession('1939948488484')
#8 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(942): App\Controllers\Bot->botApi()
#9 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
#10 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wa-bot\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(85): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(27): App\Controllers\Bot->getSession('1939948488484')
#7 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(942): App\Controllers\Bot->botApi()
#8 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
#9 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wa-bot\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-11-12 20:58:13 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `bot_follow_up`
WHERE `user_id` = :user_id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Bot.php(85): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Bot.php(27): App\Controllers\Bot->getSession('1939948488484')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-12 20:58:14 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'real_estate', 3306, '', 0)
#1 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(85): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(27): App\Controllers\Bot->getSession('1939948488484')
#8 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(942): App\Controllers\Bot->botApi()
#9 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
#10 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wa-bot\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(85): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php(27): App\Controllers\Bot->getSession('1939948488484')
#7 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(942): App\Controllers\Bot->botApi()
#8 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
#9 C:\xampp\htdocs\wa-bot\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wa-bot\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-11-12 20:58:14 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `bot_follow_up`
WHERE `user_id` = :user_id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Bot.php(85): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Bot.php(27): App\Controllers\Bot->getSession('1939948488484')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-12 21:57:45 --> App\Controllers\Bot::getSession(): Argument #1 ($sender) must be of type string, null given, called in C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php on line 27
in APPPATH\Controllers\Bot.php on line 91.
 1 APPPATH\Controllers\Bot.php(27): App\Controllers\Bot->getSession(null)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-12 21:58:05 --> App\Controllers\Bot::getSession(): Argument #1 ($sender) must be of type string, null given, called in C:\xampp\htdocs\wa-bot\app\Controllers\Bot.php on line 27
in APPPATH\Controllers\Bot.php on line 91.
 1 APPPATH\Controllers\Bot.php(27): App\Controllers\Bot->getSession(null)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-12 22:05:17 --> Cannot use temporary expression in write context
in APPPATH\Controllers\Bot.php on line 41.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-12 22:05:35 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 930.
 1 SYSTEMPATH\BaseModel.php(930): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update(null, [])
 3 APPPATH\Controllers\Bot.php(155): CodeIgniter\Model->update()
 4 APPPATH\Controllers\Bot.php(40): App\Controllers\Bot->update_status('1939948488484')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-12 22:06:51 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 930.
 1 SYSTEMPATH\BaseModel.php(930): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update(null, [])
 3 APPPATH\Controllers\Bot.php(155): CodeIgniter\Model->update()
 4 APPPATH\Controllers\Bot.php(40): App\Controllers\Bot->update_status('1939948488484')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-12 22:09:50 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 930.
 1 SYSTEMPATH\BaseModel.php(930): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update(null, [])
 3 APPPATH\Controllers\Bot.php(155): CodeIgniter\Model->update()
 4 APPPATH\Controllers\Bot.php(40): App\Controllers\Bot->update_status('1939948488484')
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-12 22:10:38 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1726.
 1 SYSTEMPATH\BaseModel.php(1726): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(916): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\Bot.php(154): CodeIgniter\Model->update([...])
 5 APPPATH\Controllers\Bot.php(40): App\Controllers\Bot->update_status('1939948488484')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Bot->botApi()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Bot))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
